### ISSUE TITLE
Version 1.3.0 Release Checklist

### ISSUE THREAD

**Issue by IGJoshua** [IGJoshua/discljord#89]
I keep forgetting what needs done before we release 1.3.0. This checklist will keep everything that needs done in one place.

- [x] Generate Codox Documentation (remember this doesn't work on JDK 16+)
- [x] Update readme examples to use intents
- [x] Channel Slash command options
- [x] Deprecate the `embed` parameter and use `embeds` in the public function
- [x] Ensure that the message content intent can be used
- [x] Fix #88 

Anything else that must happen before the release of 1.3.0 should be mentioned here. If it needs done before 1.3.0 it will be added to this post. Otherwise I'll create issues to track them.
